services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - '${APP_PORT:-3000}:3000'
    environment:
      - NODE_ENV=production
      - APP_PORT=${APP_PORT:-3000}
      - APP_NAME=${APP_NAME}
      - API_PREFIX=${API_PREFIX}
      - APP_FALLBACK_LANGUAGE=${APP_FALLBACK_LANGUAGE}
      - APP_HEADER_LANGUAGE=${APP_HEADER_LANGUAGE}
      - FRONTEND_DOMAIN=${FRONTEND_DOMAIN}
      - BACKEND_DOMAIN=${BACKEND_DOMAIN}
      - DATABASE_TYPE=${DATABASE_TYPE}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_SYNCHRONIZE=${DATABASE_SYNCHRONIZE:-false}
      - DATABASE_MAX_CONNECTIONS=${DATABASE_MAX_CONNECTIONS:-100}
      - DATABASE_SSL_ENABLED=${DATABASE_SSL_ENABLED:-true}
      - DATABASE_REJECT_UNAUTHORIZED=${DATABASE_REJECT_UNAUTHORIZED:-false}
      - DATABASE_CA=${DATABASE_CA}
      - DATABASE_KEY=${DATABASE_KEY}
      - DATABASE_CERT=${DATABASE_CERT}
      - AUTH_JWT_SECRET=${AUTH_JWT_SECRET}
      - AUTH_JWT_TOKEN_EXPIRES_IN=${AUTH_JWT_TOKEN_EXPIRES_IN}
      - AUTH_REFRESH_SECRET=${AUTH_REFRESH_SECRET}
      - AUTH_REFRESH_TOKEN_EXPIRES_IN=${AUTH_REFRESH_TOKEN_EXPIRES_IN}
      - AUTH_CONFIRM_EMAIL_SECRET=${AUTH_CONFIRM_EMAIL_SECRET}
      - AUTH_CONFIRM_EMAIL_TOKEN_EXPIRES_IN=${AUTH_CONFIRM_EMAIL_TOKEN_EXPIRES_IN}
      - AUTH_FORGOT_SECRET=${AUTH_FORGOT_SECRET}
      - AUTH_FORGOT_TOKEN_EXPIRES_IN=${AUTH_FORGOT_TOKEN_EXPIRES_IN}
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_USER=${MAIL_USER}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_IGNORE_TLS=${MAIL_IGNORE_TLS}
      - MAIL_SECURE=${MAIL_SECURE}
      - MAIL_REQUIRE_TLS=${MAIL_REQUIRE_TLS}
      - MAIL_DEFAULT_EMAIL=${MAIL_DEFAULT_EMAIL}
      - MAIL_DEFAULT_NAME=${MAIL_DEFAULT_NAME}
      - MAIL_CLIENT_PORT=${MAIL_CLIENT_PORT}
      - FILE_DRIVER=${FILE_DRIVER}
      - ACCESS_KEY_ID=${ACCESS_KEY_ID}
      - SECRET_ACCESS_KEY=${SECRET_ACCESS_KEY}
      - AWS_S3_REGION=${AWS_S3_REGION}
      - AWS_DEFAULT_S3_BUCKET=${AWS_DEFAULT_S3_BUCKET}
      - WORKER_HOST=${WORKER_HOST}
      - WORKER_PORT=${WORKER_PORT}
      - WORKER_USERNAME=${WORKER_USERNAME}
      - WORKER_PASSWORD=${WORKER_PASSWORD}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'wget', '--no-verbose', '--tries=1', '--spider', 'http://localhost:3000/api/v1/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
